/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeiyanRouteImport } from './routes/weiyan'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RoomRouteImport } from './routes/room'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as EmotionRouteImport } from './routes/emotion'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as BagRouteImport } from './routes/bag'
import { Route as IndexRouteImport } from './routes/index'

const WeiyanRoute = WeiyanRouteImport.update({
  id: '/weiyan',
  path: '/weiyan',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionRoute = EmotionRouteImport.update({
  id: '/emotion',
  path: '/emotion',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/challenges': typeof ChallengesRoute
  '/emotion': typeof EmotionRoute
  '/friends': typeof FriendsRoute
  '/room': typeof RoomRoute
  '/shop': typeof ShopRoute
  '/weiyan': typeof WeiyanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/challenges': typeof ChallengesRoute
  '/emotion': typeof EmotionRoute
  '/friends': typeof FriendsRoute
  '/room': typeof RoomRoute
  '/shop': typeof ShopRoute
  '/weiyan': typeof WeiyanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/challenges': typeof ChallengesRoute
  '/emotion': typeof EmotionRoute
  '/friends': typeof FriendsRoute
  '/room': typeof RoomRoute
  '/shop': typeof ShopRoute
  '/weiyan': typeof WeiyanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bag'
    | '/challenges'
    | '/emotion'
    | '/friends'
    | '/room'
    | '/shop'
    | '/weiyan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bag'
    | '/challenges'
    | '/emotion'
    | '/friends'
    | '/room'
    | '/shop'
    | '/weiyan'
  id:
    | '__root__'
    | '/'
    | '/bag'
    | '/challenges'
    | '/emotion'
    | '/friends'
    | '/room'
    | '/shop'
    | '/weiyan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BagRoute: typeof BagRoute
  ChallengesRoute: typeof ChallengesRoute
  EmotionRoute: typeof EmotionRoute
  FriendsRoute: typeof FriendsRoute
  RoomRoute: typeof RoomRoute
  ShopRoute: typeof ShopRoute
  WeiyanRoute: typeof WeiyanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weiyan': {
      id: '/weiyan'
      path: '/weiyan'
      fullPath: '/weiyan'
      preLoaderRoute: typeof WeiyanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotion': {
      id: '/emotion'
      path: '/emotion'
      fullPath: '/emotion'
      preLoaderRoute: typeof EmotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BagRoute: BagRoute,
  ChallengesRoute: ChallengesRoute,
  EmotionRoute: EmotionRoute,
  FriendsRoute: FriendsRoute,
  RoomRoute: RoomRoute,
  ShopRoute: ShopRoute,
  WeiyanRoute: WeiyanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
